### ISSUE TITLE
Any idea of error in "yolo_layer.py" 196 line?

### ISSUE THREAD

**Issue by LDCCVision** [motokimura/PyTorch_Gaussian_YOLOv3#15]
I did train with my own dataset and it worked well.

But When I try with more complex dataset(at least 50 bbox-densley packed in one image), error was occured in "yolo_layer.py" 196 line (obj_mask[b, a, j, i] = 1)

------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 197, in main
    loss = model(imgs, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/PyTorch_Gaussian_YOLOv3/models/yolov3.py", line 154, in forward
    x, *loss_dict = module(x, targets)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/PyTorch_Gaussian_YOLOv3/models/yolo_layer.py", line 209, in forward
    obj_mask[b, a, j, i] = 1
IndexError: index 44 is out of bounds for dimension 0 with size 38
-----------------------------------------------------------------------------

It means that I index out of range of variable obj_mask.
obj_mask has only length 38 in last dimension([ , , , ~38]), but index variable "i" value was 44. this value comes from "truth_i[ti]" and it comes from "truth_i = truth_i_all[b, :n]"(line 168)

I could avoid problems indirectly with put statement like
   if fsize <= i:
           continue
before line 196

Do you have any idea why this things happen??

Other detail configuration(library version, .cfg) was exactly same.

**Comment by LDCCVision** [comment]
! Self Solved !
It was caused from error of my own dataset.
some width, height value of image was confused.

**Comment by imlixinyang** [comment]
Could you share how you fix this bug? I've met the same problem and don't know why.

**Comment by LDCCVision** [comment]
> Could you share how you fix this bug? I've met the same problem and don't know why.

My image and annotation was confused at width and height. 
Ex) Originally, Width > height.. but anno has height < width (no idea why)
it makes out of bound of bbox

**Comment by motokimura** [comment]
Hi @LDCCVision, sorry for my late response and thanks for reporting.
I'm closing this issue.
