### ISSUE TITLE
How to train and test on datasets like UA-DETRAC, cityflow(ai city 2019) and pascal voc?

### ISSUE THREAD

**Issue by sisrfeng** [motokimura/PyTorch_Gaussian_YOLOv3#16]
Is the easiest way converting other datasets to COCO format and using this repo?
Should I use the code given by the author of the ICCV paper?

**Comment by motokimura** [comment]
Hi @sisrfeng. Sorry for late response.

I have no idea whether the official repo provides the converter or not.
If it has, you can customize it maybe.
Even if not, I guess it is not so difficult to write from scratch.
