### ISSUE TITLE
some things with yolo_layer.py

### ISSUE THREAD

**Issue by longmao-yiran** [motokimura/PyTorch_Gaussian_YOLOv3#19]
Hi @motokimura,
Thanks for your great implementation! 👍
I have found some things wrong with yolo_layer.py
1.https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/b51eb917ede2a1d7bc6eb0e220bf330f43baf842/models/yolo_layer.py#L209
Is there a parenthesis missing like:tgt_scale[b, a, j, i, :] =(2 - truth_w_all[b, ti] * truth_h_all[b, ti] )/ fsize / fsize
2.https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/b51eb917ede2a1d7bc6eb0e220bf330f43baf842/models/yolo_layer.py#L237
the gaussian mode fuction is torch.sqrt(2.0 * np.pi) ,not torch.sqrt(2.0 * np.pi * var)
Or maybe I got it wrong,
Welcome to point out mistakes

**Comment by longmao-yiran** [comment]
sorry，the first problem is my wrong

**Comment by motokimura** [comment]
Hi @longmao-yiran,
sorry for late response. Thanks!

As for the second question, `torch.sqrt(2.0 * np.pi * var)` seems to be correct according to the definition of gaussian distribution (see probability density function in the page below).
https://en.wikipedia.org/wiki/Normal_distribution

**Comment by longmao-yiran** [comment]
Thank you for the response
as for the probability density function in the page below https://en.wikipedia.org/wiki/Normal_distribution
I think the denominator is `torch.sqrt(2.0 * np.pi )* var` not `torch.sqrt(2.0 * np.pi * var)`

**Comment by motokimura** [comment]
In my implementation, `var` (variance) is defined as the square of `sigma`.
So `torch.sqrt(2.0 * np.pi * var)` = `torch.sqrt(2.0 * np.pi) * torch.sqrt(sigma ** 2.0)` = `torch.sqrt(2.0 * np.pi) * sigma`. 
This exactly matches with the denominator of normal distribution pdf.
