### ISSUE TITLE
How did you get the anchors on COCO？

### ISSUE THREAD

**Issue by sisrfeng** [motokimura/PyTorch_Gaussian_YOLOv3#20]
ANCHORS in your code is 
: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]

Would you mind telling me how you get the anchors or sharing the code? I want to get anchors on another dataset.
Many thanks！

**Comment by motokimura** [comment]
I just used the anchors defined in this repo I forked.
https://github.com/DeNA/PyTorch_YOLOv3

Maybe this blog post is what you need.
https://lars76.github.io/object-detection/k-means-anchor-boxes/
It provides detailed explanation and python codes to compute anchors from annotated bounding boxes.
