### ISSUE TITLE
Do you have a plan to support YOLO v3-tiny

### ISSUE THREAD

**Issue by ni4muraano** [motokimura/PyTorch_Gaussian_YOLOv3#21]
Thanks for your great work.
By the way, do you have a plan to support YOLO v3-tiny in this repo?

**Comment by motokimura** [comment]
Thanks!
I have no plan at this moment. Your PR is more than welcome!

**Comment by ni4muraano** [comment]
Thanks for your reply. I understand no plan for tiny version.
