### ISSUE TITLE
UserWarning: nn.Upsample is deprecated. 

### ISSUE THREAD

**Issue by sisrfeng** [motokimura/PyTorch_Gaussian_YOLOv3#24]
Hi, I met this:

```
/home/docker/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/docker/.pyenv/versions/3.6.8/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/work/g/utils/utils.py:41: RuntimeWarning: invalid value encountered in multiply
  area = np.prod(br - tl, axis=1) * (tl < br).all(axis=1)
/work/g/utils/utils.py:44: RuntimeWarning: invalid value encountered in greater_equal
  if (iou >= thresh).any():
/work/g/utils/utils.py:43: RuntimeWarning: invalid value encountered in subtract
  iou = area / (bbox_area[i] + bbox_area[selec] - area)
/work/g/utils/utils.py:43: RuntimeWarning: invalid value encountered in true_divide
  iou = area / (bbox_area[i] + bbox_area[selec] - area)
```

It does not continue.
Some people say we can ignore this UserWarning: nn.Upsample is deprecated. 
Can I?

**Comment by motokimura** [comment]
Hi, I guess so.

**Comment by motokimura** [comment]
You can ignore this warning as long as you use torch==1.0.0.
I do not know the code works correctly with other versions though.

**Comment by jicongh** [comment]
> Hi, I met this:
> 
> ```
> /home/docker/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
>   warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
> /home/docker/.pyenv/versions/3.6.8/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
>   return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> /work/g/utils/utils.py:41: RuntimeWarning: invalid value encountered in multiply
>   area = np.prod(br - tl, axis=1) * (tl < br).all(axis=1)
> /work/g/utils/utils.py:44: RuntimeWarning: invalid value encountered in greater_equal
>   if (iou >= thresh).any():
> /work/g/utils/utils.py:43: RuntimeWarning: invalid value encountered in subtract
>   iou = area / (bbox_area[i] + bbox_area[selec] - area)
> /work/g/utils/utils.py:43: RuntimeWarning: invalid value encountered in true_divide
>   iou = area / (bbox_area[i] + bbox_area[selec] - area)
> ```
> 
> It does not continue.
> Some people say we can ignore this UserWarning: nn.Upsample is deprecated.
> Can I?

please let me know have you solve this problem?

**Comment by sisrfeng** [comment]
I just ignore this:  UserWarning: nn.Upsample is deprecated.
It continues after about 2 hours.
