### ISSUE TITLE
Should some 'tfboard' be replaced with 'tfboard_dir' ?

### ISSUE THREAD

**Issue by sisrfeng** [motokimura/PyTorch_Gaussian_YOLOv3#26]
parser.add_argument(
        '--tfboard', help='tensorboard path for logging', type=str, default=None)

example:   
```bash
$ python train.py --cfg config/gaussian_yolov3_default.cfg --weights_path weights/darknet53.conv.74 --tfboard log

But some place is tfboard_dir.

**Comment by motokimura** [comment]
Thanks! Fixed it at https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/pull/27.
