### ISSUE TITLE
Note that with the release of Docker 19.03, usage of nvidia-docker2 packages are deprecated

### ISSUE THREAD

**Issue by sisrfeng** [motokimura/PyTorch_Gaussian_YOLOv3#28]
$ nvidia-docker build -t yolov3-in-pytorch-image --build-arg UID=`id -u` -f docker/Dockerfile .
Should be 
$ docker build -t yolov3-in-pytorch-image --build-arg UID=`id -u` -f docker/Dockerfile .

$ nvidia-docker run -it -v `pwd`:/work --name yolov3-in-pytorch-container yolov3-in-pytorch-image
should be 
docker run --gpus all  -it -v `pwd`:/work --name yolov3-in-pytorch-container yolov3-in-pytorch-image

REF:
https://github.com/NVIDIA/nvidia-docker

**Comment by motokimura** [comment]
Thanks.
Currently I have no time to workaround with docker so your PR to README is more than welcome.
