### ISSUE TITLE
seed setting for reproducibility

### ISSUE THREAD

**Issue by chengcchn** [motokimura/PyTorch_Gaussian_YOLOv3#31]
Hi, motokimura! Thanks for the nice repo!
I notice that you add the seed setting for the trainging. But I still cannot get the same result after several tries. Is it due to the randomness of the underlying implementation of Pytorch, such as the cuda implementation of the up-sample layer. I found that there are up-sample layers in the architecture of YOLOv3. Any suggestions?

**Comment by motokimura** [comment]
Hi @chengcchn. Thanks!
As you mentioned, the code produces different results every run even with the same seed.
I tried to figure out the reason why this happens, but no luck.

When I tried different backbones which don't have up-sampling layers, the seed works and the code produces the same result.
So I guess up-sampling layers have something to do with this issue as you said.
