### ISSUE TITLE
Gaussian Loss: when sigma of x, y, w,h is small wnough, gaussian loss is possible be negative number

### ISSUE THREAD

**Issue by jicongh** [motokimura/PyTorch_Gaussian_YOLOv3#35]
when sigma of x, y, w,h is small wnough, gaussian loss is possible be negative number
Is there any detail I didn't notice？
thank for your contribution

**Comment by motokimura** [comment]
Gaussian loss can become negative but this is not a problem as the gradient (not loss value itself) is important for learning.
