### ISSUE TITLE
Can I get gaussian_yolov3_coco.pth file?

### ISSUE THREAD

**Issue by YeonjeeJung** [motokimura/PyTorch_Gaussian_YOLOv3#37]
Hi.

Can you share ./gaussian_yolov3_coco.pth file?

And can I use .ckpt file in demo, not .pth file?

If not, how can I use .ckpt file?

**Comment by motokimura** [comment]
Hi, 
you can load .ckpt file as demo.ipynb does.
If you sitll need .pth file, load .ckpt file and then save the model weight with `torch.save()`.

**Comment by YeonjeeJung** [comment]
Ok, then can you share the trained final file?

**Comment by motokimura** [comment]
Please read [this section](https://github.com/motokimura/PyTorch_Gaussian_YOLOv3#inference-with-pretrained-weights).
You can download the checkpoint file (`the trained final file` you said) from our GoogleDrive.
