### ISSUE TITLE
Where the uncertainty value is used?

### ISSUE THREAD

**Issue by YeonjeeJung** [motokimura/PyTorch_Gaussian_YOLOv3#38]
In original paper, they used uncertainty score in detection criterion.

So I understood that value is used in nms function.

But your code doesn't use uncertainty value for detection, and just shows the dashed boundary.

Did I understood wrong? If I did, where the uncertainty value is used?

Thanks.

**Comment by motokimura** [comment]
Hi @YeonjeeJung,

At inference time, the objectness confidence is decayed by uncertainty score:
https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/master/models/yolo_layer.py#L123-L125

Does this answer your question?

**Comment by YeonjeeJung** [comment]
thanks!
