### ISSUE TITLE
Question about NLL

### ISSUE THREAD

**Issue by youngwanLEE** [motokimura/PyTorch_Gaussian_YOLOv3#39]
Hi, 

I'm impressed by your wonderful work.

When I read the gaussian [YOLOv3 original code repo](https://github.com/jwchoi384/Gaussian_YOLOv3) and compare it with your implementation, I came across a curious thing.

In original code,
[`float in_exp_x = (tx - x[index + 0*stride])/x[index+1*stride];`](https://github.com/jwchoi384/Gaussian_YOLOv3/blob/7d2ab7c927414f912a647c93ce807fbfb448255e/src/gaussian_yolo_layer.c#L107)

`sqrt(tx - mean)/var`

where tx is the target, mean and variance is the predicted coordinate and variance of bbox in the detection layer, respectively.

However,

in your code,
https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/3b679c8d6fec51f6f689a33d72e6dd85c4195f62/models/yolo_layer.py#L223

tx <->  mean are ex-changed in https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/3b679c8d6fec51f6f689a33d72e6dd85c4195f62/models/yolo_layer.py#L236

If I misunderstand this, can you fix me? 

Thanks in advance.

**Comment by motokimura** [comment]
Hi @youngwanLEE,
thank you for your interest in my project!

In my implementation, only the absolute value of each element in `val - mean` is important. 
i.e., `_gaussian_dist_pdf` returns the same value even if you exchange `val` and `mean`.

Does this answer your question?

**Comment by youngwanLEE** [comment]
@motokimura 
Thanks for your reply :)

**Comment by youngwanLEE** [comment]
@motokimura 
Hi, 
I have another question.

I cannot figure out why you unnormalize the uncertainties.

Could you explain? 

https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/3b679c8d6fec51f6f689a33d72e6dd85c4195f62/models/yolo_layer.py#L127-L130

Thanks in advance :)

**Comment by motokimura** [comment]
Hi @youngwanLEE,

that is just for the visualization purpose.
If you want to interpret predicted uncertainties in image coordinate as some pictures shown in my README.md, you need this.
You dont't need this if you just want to train and test the model.

Let me know if you need more details!

**Comment by youngwanLEE** [comment]
@motokimura 
Many thanks :)
