### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator

### ISSUE THREAD

**Issue by iamlvm** [motokimura/PyTorch_Gaussian_YOLOv3#41]
Hi @motokimura,
I got an error while training happened on Pytorch 1.2.

`Setting Arguments.. :  Namespace(cfg='D:\\temp\\objectdetection\\PyTorch_Gaussian_YOLOv3-master\\config\\gaussian_yolov3_default.cfg', checkpoint=None, checkpoint_dir='checkpoints', checkpoint_interval=1000, debug=False, eval_interval=4000, n_cpu=0, tfboard_dir='D:\\temp\\objectdetection\\PyTorch_Gaussian_YOLOv3-master\\log', use_cuda=True, weights_path='D:\\temp\\objectdetection\\PyTorch_Gaussian_YOLOv3-master\\weights\\darknet53.conv.74')
successfully loaded config file:  {'MODEL': {'TYPE': 'YOLOv3', 'BACKBONE': 'darknet53', 'ANCHORS': [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], 'ANCH_MASK': [[6, 7, 8], [3, 4, 5], [0, 1, 2]], 'N_CLASSES': 80, 'GAUSSIAN': True}, 'TRAIN': {'LR': 0.001, 'MOMENTUM': 0.9, 'DECAY': 0.0005, 'BURN_IN': 1000, 'MAXITER': 500000, 'STEPS': '(400000, 450000)', 'BATCHSIZE': 4, 'SUBDIVISION': 16, 'IMGSIZE': 608, 'LOSSTYPE': 'l2', 'IGNORETHRE': 0.7, 'GRADIENT_CLIP': 2000.0}, 'AUGMENTATION': {'RANDRESIZE': True, 'JITTER': 0.3, 'RANDOM_PLACING': True, 'HUE': 0.1, 'SATURATION': 1.5, 'EXPOSURE': 1.5, 'LRFLIP': True, 'RANDOM_DISTORT': True}, 'TEST': {'CONFTHRE': 0.8, 'NMSTHRE': 0.45, 'IMGSIZE': 416}, 'NUM_GPUS': 1}
effective_batch_size = batch_size * iter_size = 4 * 16
Gaussian YOLOv3
Gaussian YOLOv3
Gaussian YOLOv3
loading darknet weights.... D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\weights\darknet53.conv.74
using cuda
using tfboard
loading annotations into memory...
Done (t=19.05s)
creating index...
index created!
loading annotations into memory...
Done (t=1.04s)
creating index...
index created!
evaluating...
C:\Users\computer\Anaconda3\envs\yolo\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\utils\utils.py:44: RuntimeWarning: invalid value encountered in greater_equal
  if (iou >= thresh).any():
D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\utils\utils.py:43: RuntimeWarning: invalid value encountered in subtract
  iou = area / (bbox_area[i] + bbox_area[selec] - area)
D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\utils\utils.py:41: RuntimeWarning: invalid value encountered in multiply
  area = np.prod(br - tl, axis=1) * (tl < br).all(axis=1)
D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\utils\utils.py:43: RuntimeWarning: invalid value encountered in true_divide
  iou = area / (bbox_area[i] + bbox_area[selec] - area)
Loading and preparing results...
DONE (t=40.17s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=56.08s).
Accumulating evaluation results...
DONE (t=19.75s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.028
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.062
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.071
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.073
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.078

Traceback (most recent call last):
  File "D:/temp/objectdetection/PyTorch_Gaussian_YOLOv3-master/train.py", line 237, in <module>
    main()
  File "D:/temp/objectdetection/PyTorch_Gaussian_YOLOv3-master/train.py", line 185, in main
    loss = model(imgs, targets)
  File "C:\Users\computer\Anaconda3\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\models\yolov3.py", line 154, in forward
    x, *loss_dict = module(x, targets)
  File "C:\Users\computer\Anaconda3\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\temp\objectdetection\PyTorch_Gaussian_YOLOv3-master\models\yolo_layer.py", line 187, in forward
    obj_mask[b] = 1 - pred_best_iou
  File "C:\Users\computer\Anaconda3\envs\yolo\lib\site-packages\torch\tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.`

**Comment by Romaosir** [comment]
@JohnPekl 
# obj_mask[b] = 1 - pred_best_iou
obj_mask[b] = ~pred_best_iou

**Comment by Romaosir** [comment]
@JohnPekl 
‘#obj_mask[b] = 1 - pred_best_iou
obj_mask[b] = ~pred_best_iou
