### ISSUE TITLE
Does this sentence mean total uncertainty? thanks for the reply! !     pred[..., 4] *= (1.0 - sigma)

### ISSUE THREAD

**Issue by xiaozhangya** [motokimura/PyTorch_Gaussian_YOLOv3#45]
Does this sentence mean total uncertainty? thanks for the reply! !   pred[..., 4] *= (1.0 - sigma)

**Comment by motokimura** [comment]
That equation corresponds to eq. 10 of [the original paper](https://arxiv.org/pdf/1904.04620.pdf).

`sigma` is the mean of the uncertainties for x, y, w, and h coords
(`sigma` shape is `[batch, anchor x grid_y x grid_x]`).

`pred[..., 4]` is object confidences.
