### ISSUE TITLE
how the sigmas will be used in testing

### ISSUE THREAD

**Issue by harlem867** [motokimura/PyTorch_Gaussian_YOLOv3#8]
@motokimura  hello, motokimura, thank you for this great project!
In the paper of gaussian yolov3, the mean of sigma_x,sigma_y,sigma_w,sigma_h will be used to calculate the uncertainty, and (1-uncertainty) will be multiplied with obj_conf and class_conf.

How do you use the sigmas while testing in this code？
I didn't find in the function of postprocess. Thank you!

**Comment by motokimura** [comment]
Hi @harlem867!
(1 - uncertainty) is multiplied to obj_conf at [these lines](https://github.com/motokimura/PyTorch_Gaussian_YOLOv3/blob/b51eb917ede2a1d7bc6eb0e220bf330f43baf842/models/yolo_layer.py#L121-L125).
After this operation, `pred` is input to `postprocess()` function.
