### ISSUE TITLE
what's the meaning of tgt_scale?

### ISSUE THREAD

**Issue by shadowclouds** [motokimura/PyTorch_Gaussian_YOLOv3#9]
Could you please tell me what's the meaning of tgt_scale that you use:
 loss_xy = (loss_xy * tgt_scale).sum()
 loss_wh = (loss_wh * tgt_scale).sum()

**Comment by motokimura** [comment]
Hi, `tgt_scale` corresponds to eq. (9) of the [Gaussian YOLOv3 paper](https://arxiv.org/pdf/1904.04620.pdf). 
It gives higher weight to the loss of smaller objects (this was originally proposed in YOLOv3 paper).

**Comment by shadowclouds** [comment]
thanks for your quick reply!
